/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as components from "../../models/components";
import * as z from "zod";

export type CreatePetResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Pet created successfully
     */
    pet?: components.Pet | undefined;
};

/** @internal */
export namespace CreatePetResponse$ {
    export type Inbound = {
        HttpMeta: components.HTTPMetadata$.Inbound;
        Pet?: components.Pet$.Inbound | undefined;
    };

    export const inboundSchema: z.ZodType<CreatePetResponse, z.ZodTypeDef, Inbound> = z
        .object({
            HttpMeta: components.HTTPMetadata$.inboundSchema,
            Pet: components.Pet$.inboundSchema.optional(),
        })
        .transform((v) => {
            return {
                httpMeta: v.HttpMeta,
                ...(v.Pet === undefined ? null : { pet: v.Pet }),
            };
        });

    export type Outbound = {
        HttpMeta: components.HTTPMetadata$.Outbound;
        Pet?: components.Pet$.Outbound | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, CreatePetResponse> = z
        .object({
            httpMeta: components.HTTPMetadata$.outboundSchema,
            pet: components.Pet$.outboundSchema.optional(),
        })
        .transform((v) => {
            return {
                HttpMeta: v.httpMeta,
                ...(v.pet === undefined ? null : { Pet: v.pet }),
            };
        });
}
