/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as z from "zod";

/**
 * * '1' - SMS
 *
 * @remarks
 * * '2' - Email
 * * '3' - Browser
 * * '4' - Duo
 * * '5' - MicrosoftAuthenticator'
 * * '6' - No MFA
 *
 */
export enum MfaMethods {
    One = 1,
    Two = 2,
    Three = 3,
    Four = 4,
    Five = 5,
    Six = 6,
}

/** @internal */
export const MfaMethods$ = z.nativeEnum(MfaMethods);
