/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { MfaMethods, MfaMethods$ } from "./mfamethods";
import * as z from "zod";

export type Pet = {
    /**
     * Unique identifier for the Pet
     */
    id?: number | undefined;
    /**
     * Name of the pet
     */
    name?: string | undefined;
    mfaMethods?: Array<MfaMethods> | undefined;
};

/** @internal */
export namespace Pet$ {
    export type Inbound = {
        id?: number | undefined;
        name?: string | undefined;
        mfaMethods?: Array<MfaMethods> | undefined;
    };

    export const inboundSchema: z.ZodType<Pet, z.ZodTypeDef, Inbound> = z
        .object({
            id: z.number().int().optional(),
            name: z.string().optional(),
            mfaMethods: z.array(MfaMethods$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.mfaMethods === undefined ? null : { mfaMethods: v.mfaMethods }),
            };
        });

    export type Outbound = {
        id?: number | undefined;
        name?: string | undefined;
        mfaMethods?: Array<MfaMethods> | undefined;
    };

    export const outboundSchema: z.ZodType<Outbound, z.ZodTypeDef, Pet> = z
        .object({
            id: z.number().int().optional(),
            name: z.string().optional(),
            mfaMethods: z.array(MfaMethods$).optional(),
        })
        .transform((v) => {
            return {
                ...(v.id === undefined ? null : { id: v.id }),
                ...(v.name === undefined ? null : { name: v.name }),
                ...(v.mfaMethods === undefined ? null : { mfaMethods: v.mfaMethods }),
            };
        });
}
